### ISSUE TITLE
Rstudio surcharge du networking.virtual-host

### ISSUE THREAD

**Issue by MelineeTS** [InseeFrLab/Universe-Datascience#10]
On nous ment ! On nous propose de choisir son networking.virtual-host mais ce n'est pas pris en compte.

**Comment by olevitt** [comment]
Onyxia is enforcing virtualhosts. The field `networking.virtual-host` should still be honored by clients that do not enforces virtualhosts.  
We should add `x-form.visible=false` to prevent the field from being displayed on forms that follow the onyxia format extension (see https://github.com/InseeFrLab/onyxia-api/blob/master/docs/specification/README.md)

**Comment by fcomte** [comment]
this is solved
