### ISSUE TITLE
Image Ubuntu

### ISSUE THREAD

**Issue by JulieDjidji** [InseeFrLab/Universe-Datascience#38]
Salut, je souhaitais utiliser l'image d'Ubuntu mais je ne la trouve pas très ergonomique (pas de clic droit pour l'ouverture d'un terminal, docker pas installé ...) Serait-il possible de choisir une image plus complète (ou de compléter l'image utilisée actuellement) ? Celle sur la plateforme interne par exemple était bien (de mon point de vue) !

Je suis aussi surprise car l'image utilisée lorsqu'on lance le service via onyxia est dorowu/ubuntu-desktop-lxde-vnc (https://github.com/InseeFrLab/Universe-Datascience/blob/master/repo/packages/U/ubuntu/0/resource.json) et pourtant :
- il y a bien un dossier Ubuntu-vnc-base (qui est celle de aidan. campbell)
- et la référence notée dans (https://github.com/InseeFrLab/Universe-Datascience/blob/master/repo/packages/U/ubuntu/0/package.json) est https://github.com/fcwu/docker-ubuntu-vnc-desktop

Merci d'avance !

**Comment by fcomte** [comment]
Salut,

Nous avons publié une nouvelle image : https://github.com/InseeFrLab/ubuntu-vnc-dind
Cela convient il ?
