### ISSUE TITLE
Rstudio git properties are not set?

### ISSUE THREAD

**Issue by JulietteS** [InseeFrLab/Universe-Datascience#41]
It seems git config properties from the creation form (user.email and user.name) are not taken into account (I am asked to set it for the first commit).

**Comment by fcomte** [comment]
You are right. An init script is used for some package but not yet for Rstudio.

**Comment by fcomte** [comment]
This commit resolves this issue.

https://github.com/InseeFrLab/Universe-Datascience/commit/635bdac1c25dce7096c7501bb71de99c64906a95
